### ISSUE TITLE
rogcat does not respond well to sigterm

### ISSUE THREAD

**Issue by gizmomogwai** [flxo/rogcat#1]
if i send sigterm it just continues happily.

**Comment by Nicoretti** [comment]
I do not think thats an actual issue AFAIK unlike sigkill, sigterm is just a request to terminate.
@see also https://en.wikipedia.org/wiki/Unix_signal#POSIX_signals

**Comment by flxo** [comment]
I started to refactor the processing loop in the `tokio` branch where signal handling will be part of.  A open point is to forward signals to the subprocess.

**Comment by flxo** [comment]
Fixed.
