### ISSUE TITLE
Multiple devices

### ISSUE THREAD

**Issue by goncalopalaio** [flxo/rogcat#11]
Sorry if this is by chance really obvious, I know there's rogcat devices to list the available devices.
Is there an option to use the ANDROID_SERIAL to switch between devices, similar to adb -s option?

**Comment by flxo** [comment]
`rogcat` just calling `adb logcat` in the end. So setting `ANDROID_SERIAL` should work out of the box. 
There is currently no option to specify the serial on the command line but this can be easily added. Unfortunately `-s` is already taken :-/.

**Comment by goncalopalaio** [comment]
I didn't even realize that the -s option of adb overrides the ANDROID_SERIAL environment variable. That will do for now.
If I find the time I will try to add support and open a Pull request.
Many thanks, I've been using this project in my daily job instead of regular adb logcat and it is really useful.

This issue can be closed if that's appropriate.

**Comment by flxo** [comment]
You're welcome. Thanks.
