### ISSUE TITLE
toml vs xml profiles file

### ISSUE THREAD

**Issue by francozappa** [flxo/rogcat#12]
Hi,

Thanks for the tool!

I guess that `rogcat profiles --list` subcommand expects an `profiles.xml` in the config dir, however in the README you recommend to create a `profiles.toml`. Indeed if you create a toml file you will get the following error when issuing `rogcat profiles --list`

    No profiles present in "/home/username/.config/rogcat/profiles.xml"

Maybe you can change the `profiles` subcommand such that it parses (only) toml files?

**Comment by flxo** [comment]
Thanks for the report!

The readme is fine. `rogcat` doesn't use `xml` files at all and the profile file check is wrong (if not set by env var or on command line).

Fixed with [67f6dfb](https://github.com/flxo/rogcat/commit/67f6dfb26f11234286f96aab938309bdeb55d50a)
