### ISSUE TITLE
Unable to open log device 'crash'

### ISSUE THREAD

**Issue by zhang-longfei** [flxo/rogcat#18]
![image](https://user-images.githubusercontent.com/46529058/56653414-36c2c980-66c0-11e9-9d8c-0d9ce4daefe2.png)

system: windows 10

**Comment by flxo** [comment]
Hello @zhang-longfei 

Thanks for the report. Some words about your environment and target you're trying to access would be helpful.
`rogcat` by default runs `add logcat -b main events crash kernel`. Seem like your device doesn't have the crash buffer (which is Android standard). You can overwrite the rogcat default by applying the `-b` options to `rogcat` or configure the default behaviour in the config file (see Readme).

**Comment by zhang-longfei** [comment]
I don't know why, it is good now.
