### ISSUE TITLE
Filter based on PID?

### ISSUE THREAD

**Issue by gqqnbig** [flxo/rogcat#19]
Can rogcat filter based on pid?

**Comment by flxo** [comment]
Currently no - but this is trivial to add.

**Comment by flxo** [comment]
Fixed with [dd2e9d2](https://github.com/flxo/rogcat/commit/dd2e9d250e5534c7743dfca4c93851b3585a3a64) that adds `-r`/`--regex` to filter on any of pid, thread, tag, message.
