### ISSUE TITLE
Make rogcat available via crates.io

### ISSUE THREAD

**Issue by Nicoretti** [flxo/rogcat#2]
:1st_place_medal: 
```
cargo install rogcat
```

**Comment by flxo** [comment]
We still have the git dep for terminal-size because [this PR](https://github.com/eminence/terminal-size/pull/7) is still open. You cannot publish on crates.io with a non crate.io dependency.
I'll ping @eminence and see if we can get forward here.

**Comment by flxo** [comment]
I migrated to `term_size` that seems to have wider platform support and is published on crates.io.

[Fixed.](https://crates.io/crates/rogcat)
