### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by wngr** [flxo/rogcat#26]
Hey,

thanks for your project, it's a nice little helper in my daily workflow :-).

Given that there are a few things since the last release to crates.io (from May '19) – especially exposing the parser in lib – it would be great if you could cut a new release and make it more accessible like that.

Thanks!

**Comment by flxo** [comment]
Done. Thanks for the trigger!
https://github.com/flxo/rogcat/releases/tag/v0.4.1
https://crates.io/crates/rogcat
