### ISSUE TITLE
Add command line switch to select adb device

### ISSUE THREAD

**Issue by elektronenhirn** [flxo/rogcat#32]
I have a workstation where multiple android devices are connected via USB. When running rogcat it get...
```
                                                 ()  -    - waiting for device -
                                                 ()  -    error: more than one device/emulator
```
so basically the same as I would get from `adb logcat`. Could you add a command line switch to select the device by the serial number? Similar to adb's `-s` switch?

**Comment by flxo** [comment]
Adding the switch would make sense. I think there's an environment variable that can be used in the meantime: `ANDROID_SERIAL`

**Comment by elektronenhirn** [comment]
Thanks for the workaround. Running rogcat
```
ANDROID_SERIAL=9e411206 rogcat
``` 
works for me!

**Comment by flxo** [comment]
If there needs a argument passed to `logcat` you can also use `rogcat adb logcat -s SERIAL`. Together with the env variable there are two solutions.
