### ISSUE TITLE
Missing Package Requirement for Ubuntu 20.04

### ISSUE THREAD

**Issue by sameernegi17** [flxo/rogcat#39]
Following error has been observed : 

> error: failed to run custom build command for `libudev-sys v0.1.4` 
Caused by:
  process didn't exit successfully: `rogcat/target/release/build/libudev-sys-081b531eee85ba8b/build-script-build` (exit status: 101)

The reason is that package libudev-dev needs to be installed.

Command : 

> sudo apt-get install libudev-dev

**Comment by sameernegi17** [comment]
Yes. May be hint of the prerequisite packages that are needed to be installed.

**Comment by flxo** [comment]
@sameernegi17 Want to open a PR?

**Comment by flxo** [comment]
Fixed with 45c3a68
