### ISSUE TITLE
Question about features and support formats

### ISSUE THREAD

**Issue by abidesmail** [flxo/rogcat#4]
Great Tool with some awesome features. 

Can rogcat parse an existing adb logcat file? We get logcat files from the field and would like to parse them into an easily readable format.

So can it parse a file that is outputted from the command adb logcat -v threadtime > adblogs.txt

If this tool cannot do this, do you have any suggestions of other tools that can do this.

Thanks,
Abid

**Comment by flxo** [comment]
Hi,

Yes. Rogcat can read from `files`, `stdin` or run a `program`:

`rogcat -i FILE` 
 `cat FILE | rogcat -`
 `rogcat "cat FILE"`

The `-i` also can take multiple arguments that are processed in alphanumerical order:

`rogcat -i log0.txt log1.txt`

The `threadtime` format is the default and implemented in `rogcat`. The format of the input stream is detected during runtime and there is no need to specify is manually. For the output format options check the

`-f, --file-format <FILE_FORMAT>              Select format for output files [values: csv, html, raw]`

option. Reading traces from the field is one of the main purposes of `rogcat`. If you pass them to people without rogcat the `html` format option is your friend. In your case you'd probably run something like

`rogcat -i adblogs.txt -f html -o adblogs.html`

The html template is quite stupid and only works on a average workstation with up to ~50k lines quite well. Longer traces therefore can be split with the `-n` option into enumerated chunks.

`rogcat -i adblogs.txt -f html -n 10k -o adblogs.html`

Ok?

cheers,

Felix

**Comment by abidesmail** [comment]
Hi Felix,

Thanks for your quick and detailed response. Some neat features. Kudos!

So I just realized that the format of our logs are not in the standard format. Not sure why. Can I specify the input file format?  I think you mention it above, but I can't seem to figure out how to do it. 

BTW, i'm running windows 64bit.

Input log format:
06-02 09:08:02.152 V/ATS-VBS-J1708( 2169): frame  <-- 80 : B70000B8FEFF
06-02 09:08:02.184 D/dalvikvm( 2169): GC_CONCURRENT freed 389K, 11% free 5667K/6343K, paused 2ms+2ms
06-02 09:08:02.191 D/ATS-Position( 2001): Satellites: ttff = 10816058; 9 sats total; 7 sats used
06-02 09:08:02.215 V/ATS-VBS-CAN( 2169): frame  <-- 18fef100 : FCCE36C4000000F0

FYI: I found two other issues. I'll post them.

Thanks,
Abid

**Comment by flxo** [comment]
rogcat implements the standard (AOSP) format and is tested with version 4 to 7.  Your examples look like to be captured with `adb logcat -v time` (which is not supported by rogcat).

**Comment by flxo** [comment]
Did you try different formats?

**Comment by flxo** [comment]
I'll close this issue due to inactivity.
