### ISSUE TITLE
Reading file fails

### ISSUE THREAD

**Issue by bjoernbeuckesr** [flxo/rogcat#40]
Hi,
there is a issue if i wahnt to read a stored file into rogcat. The issue is on different locations, also it is no effect if I try to import a logcat log or a before stored rogcat log. I get always the message:
>Failed to open rogcat.log: `blocking` annotated I/O must be called from the context of the Tokio runtime.

No effect are also if I use the complete pathname or run it from the directory, where the file is located.
Version is: 0.4.3

Issue is not in 0.4.1 existing

**Comment by flxo** [comment]
Thanks - this is some fallout from `cf1197e`. I reverted the removal of the signal handling and the `-i` use case seems to work again. I've currently no time to investigate further.
