### ISSUE TITLE
html file format not generate file

### ISSUE THREAD

**Issue by YanceyWang** [flxo/rogcat#42]
rogcat -f html -o log.html 
cmd+c to exist rogcat, can not generate log.html file

**Comment by YanceyWang** [comment]
> Do you see output if you run `rogcat` without any ar

@flxo yeah, it works fine

**Comment by flxo** [comment]
Hm. The html format is not supported for live logs. If you need really need that, dump your log to a file and convert it afterwards

```
rogcat -o log
rogcat -i log -f html -o log.html
```

**Comment by flxo** [comment]
@YanceyWang I'm closing this. Feel free to reopen if post processing is not an option. 

The HTML output is not supported for live logs. This would be a new feature.
