### ISSUE TITLE
Quit rogcat.exe while printing makes the shell text the same color as last text

### ISSUE THREAD

**Issue by abidesmail** [flxo/rogcat#5]
If you quit rogcat.exe (via ctrl c) while it's printing, it leaves the color of the shell text as the last text color that is being printed. Probably works fine in linux.

**Comment by flxo** [comment]
Windows terminals tend to be tricky. I know from a couple of people who use [Cmdr](http://cmder.net) without any issues - maybe that's something for you. Anyway - this needs to be fixed.

**Comment by flxo** [comment]
Fixed by [#128599](https://github.com/flxo/rogcat/commit/128599e09c3774e3835c1b95672b67aac0749380)
