### ISSUE TITLE
If /dev/log/all does not exist on the device the app fails and keeps printing "Restarting..."

### ISSUE THREAD

**Issue by abidesmail** [flxo/rogcat#6]
My device is running Android 4.0.3 and it doesn't contain the /dev/log/all file, so I get the following error if I run 'rogcat.exe' over and over

Restarting "C:\Users\abid.esmail\AppData\Local\Android\sdk\platform-tools\adb.exe logcat -b all"
                                   ()  -    Unable to open log device '/dev/log/all': No such file or directory
Restarting "C:\Users\abid.esmail\AppData\Local\Android\sdk\platform-tools\adb.exe logcat -b all"
                                   ()  -    Unable to open log device '/dev/log/all': No such file or directory

shell@android:/dev/log $ ll
crw-rw--w- root     log       10,  55 2014-01-31 17:00 events
crw-rw--w- root     log       10,  56 2014-01-31 17:00 main
crw-rw--w- root     log       10,  54 2014-01-31 17:00 radio
crw-rw--w- root     log       10,  53 2014-01-31 17:00 system

Thanks,
Abid

**Comment by flxo** [comment]
Starting rogcat without any argument defaults to `adb logcat -b all` which works fine standard Android systems.
Your platform seems to not provide the `all` buffer. Doesn't mater: just provide the command yourself:

`rogcat "adb logcat"`
