### ISSUE TITLE
Error: stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by klefevre** [flxo/rogcat#8]
`rogcat` is unusable for me because the stream stop itself each time. The given reasons is the following: `Error: stream did not contain valid UTF-8`

**Comment by flxo** [comment]
The output of `logcat` is supposed to be text. Seems in your log stream someone is printing something weird. Can you please check the output of `adb logcat -b all` for something non ascii?

Maybe `rogcat` should replace non printable stuff with some kind of placeholder.

**Comment by drahnr** [comment]
How about replacing unprintable characters with `\xVAL`? Would keep the information intact without killing the stream.

**Comment by flxo** [comment]
There is [String::from_utf8_lossy](https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8_lossy) which uses `U+FFFD` as a replacement. Not sure how to effectively iterate over the array and check for UTF8 validity.

**Comment by drahnr** [comment]
Well, utf8 is multibyte to essentially you would need to start from a known good and then have a state machine, I think it can be done pretty efficiently but tbh `*_lossy` is good enough.

**Comment by klefevre** [comment]
@flxo  Here is a sentence that make stop `rogcat` but work with `logcat`:

```bash
08-29 15:40:12.273 11909 12010 V G2P-SRPOL: After conversion: Paramètres, Param�tres, 11, 10
```

**Comment by flxo** [comment]
Thanks for the report!

I pushed [#5c0194](https://github.com/flxo/rogcat/commit/5c01945b92cce3a648d0d3a7070b68a575f02b45) which allows non UTF8 bytes in the input. They will be replaced with `�`. Seems like some people put weird stuff into their logs ;-).
